import cowsay
print("------------- Cow ----------------\n")
cowsay.cow("Hello, world")
print("\n\n")
print("-------------- Tux ---------------\n")
cowsay.tux("Hi")
print("\n\n")
print("-------------- dragon ---------------\n")
cowsay.dragon("Fear me!")
print("\n\n")
print("-------------- Ghost ---------------\n")
cowsay.ghostbusters("Who ya gonna call!")
print("\n\n")
print("-------------- Turkey ---------------\n")
cowsay.turkey("Gobble gobble !")
print("\n\n")
print("-------------- Pig ---------------\n")
cowsay.pig("Oink Oink!")
print("\n\n")
print("-------------- Beavis ---------------\n")
cowsay.beavis("Hey hey!")
print()


